name: Update Manifest on Develop Change

on:
  push:

jobs:
  detect-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get current version
        id: frontend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'kimyoungwoo613/grayround:\K[0-9]+\.[0-9]+' websource/deploy.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=1.0
          fi
          NEW_VERSION=$(echo $CURRENT_VERSION + 1.0 | bc)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Build and Push Image
        run: |
          docker build -t kimyoungwoo613/grayround:${{ env.NEW_VERSION }} .
          docker push kimyoungwoo613/grayround:${{ env.NEW_VERSION }}
      - name: Update deploy.yaml
        run: |
          sed -i 's|image: kimyoungwoo613/grayround:.*|image: kimyoungwoo613/grayround:${{ env.NEW_VERSION }}|' websource/deploy.yaml
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add websource/deploy.yaml
          git commit -m "Update Docker images and change image to version ${{ env.NEW_VERSION }}"
          git push origin main
